# Generated by Django 4.2 on 2023-04-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='alumnos',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='profesores',
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Asignatura',
        ),
    ]
