# Generated by Django 4.2 on 2023-04-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alumno_asignatura_profesor_correo_electronico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='profesorasignatura',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='profesorasignatura',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='correo_electronico',
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Asignatura',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
        migrations.DeleteModel(
            name='ProfesorAsignatura',
        ),
    ]
