# Generated by Django 4.0.8 on 2023-04-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='correo_electronico',
            new_name='email',
        ),
    ]
