# Generated by Django 4.0.8 on 2023-04-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alumno_asignaturas_profesor_asignaturas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='asignaturas',
            field=models.ManyToManyField(to='api.asignatura'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='asignaturas',
            field=models.ManyToManyField(to='api.asignatura'),
        ),
    ]
