# Generated by Django 4.0.8 on 2023-04-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_alumno_asignaturas_alter_profesor_asignaturas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesorasignatura',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='profesorasignatura',
            name='profesor',
        ),
        migrations.DeleteModel(
            name='AlumnoAsignatura',
        ),
        migrations.DeleteModel(
            name='ProfesorAsignatura',
        ),
    ]
