# Generated by Django 4.0.8 on 2023-04-26 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_profesorasignatura_asignatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='academia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.academia'),
        ),
    ]
