# Generated by Django 4.0.8 on 2023-04-24 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_correo_electronico_alumno_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='eventos',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='profesorasignatura',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='profesorasignatura',
            name='profesor',
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Asignatura',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.DeleteModel(
            name='ProfesorAsignatura',
        ),
    ]
