# Generated by Django 4.0.8 on 2023-04-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alumnoasignatura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
