# Generated by Django 4.0.8 on 2023-04-24 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delete_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnoasignatura',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alumno'),
        ),
    ]
