# Generated by Django 4.0.8 on 2023-04-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_alumnoasignatura_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='asignaturas',
            field=models.ManyToManyField(null=True, to='api.asignatura'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='asignaturas',
            field=models.ManyToManyField(null=True, to='api.asignatura'),
        ),
    ]
