# Generated by Django 4.0.8 on 2023-04-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='clases',
            field=models.ManyToManyField(to='academia.evento'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
