# Generated by Django 4.0.8 on 2023-05-08 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academia.curso'),
        ),
        migrations.AddField(
            model_name='evento',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academia.profesor'),
        ),
        migrations.AddField(
            model_name='curso',
            name='academia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academia.academia'),
        ),
        migrations.AddField(
            model_name='boletin',
            name='alumno',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academia.alumno'),
        ),
        migrations.AddField(
            model_name='boletin',
            name='curso',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='academia.curso'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ManyToManyField(to='academia.curso'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='evento',
            field=models.ManyToManyField(to='academia.evento'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
