# Generated by Django 4.0.8 on 2023-05-09 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_remove_alumno_curso_alter_evento_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='evento',
        ),
        migrations.AlterField(
            model_name='boletin',
            name='alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletines', to='academia.alumno'),
        ),
        migrations.AlterField(
            model_name='boletin',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boletines', to='academia.curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='academia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='academia.academia'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='academia.curso'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='academia.profesor'),
        ),
        migrations.AlterUniqueTogether(
            name='boletin',
            unique_together={('curso', 'trimestre', 'alumno')},
        ),
    ]
