# Generated by Django 4.0.8 on 2023-06-02 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_profesor_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='academia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='academia.academia'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='academia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesores', to='academia.academia'),
        ),
    ]
