# Generated by Django 4.0.8 on 2023-05-09 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_remove_alumno_evento_alter_boletin_alumno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('academia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aula', to='academia.academia')),
            ],
            options={
                'unique_together': {('nombre', 'academia')},
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='aula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='academia.aula'),
        ),
        migrations.AlterUniqueTogether(
            name='evento',
            unique_together={('dia_semana', 'hora_inicio', 'aula')},
        ),
    ]
