# Generated by Django 4.0.8 on 2023-06-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0005_alumno_academia_profesor_academia'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='alumnos/'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nombre_madre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nombre_padre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono_madre',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono_padre',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profesores/'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='telefono',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
