# Generated by Django 4.0.8 on 2023-06-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0006_alumno_fecha_nacimiento_alumno_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='alumno.jpeg', null=True, upload_to='alumnos/'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='profesor.jpeg', null=True, upload_to='profesores/'),
        ),
    ]
