# Generated by Django 4.0.8 on 2023-06-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0007_alter_alumno_foto_perfil_alter_profesor_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='alumnos/alumno.jpeg', null=True, upload_to='alumnos/'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='profesores/profesor.jpeg', null=True, upload_to='profesores/'),
        ),
    ]
