# Generated by Django 4.0.8 on 2023-06-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0009_remove_alumno_academia_remove_profesor_academia'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
