# Generated by Django 4.0.8 on 2023-06-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0010_alumno_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre_madre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre_padre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono_madre',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono_padre',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
