# Generated by Django 4.0.8 on 2023-06-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0011_alter_alumno_descripcion_alter_alumno_nombre_madre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='alumnos/AlumnoBueno.jpg', null=True, upload_to='alumnos/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, default='cursos/libro3.png', null=True, upload_to='cursos/'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='profesores/ProfesorBien.jpg', null=True, upload_to='profesores/'),
        ),
    ]
