# Generated by Django 4.0.8 on 2023-06-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tawkto_visitor_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
