# Generated by Django 4.0.8 on 2023-05-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_alter_newuser_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='groups',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
